Repository kindfi-org/kindfi, pull requests merged in 2025-02, with the labels that each got.

#105 feat(dialog): improve focus management and a11y. Fix linting errors
  apps/web/app/(routes)/project/page.tsx
  apps/web/components/base/dialog.tsx
  apps/web/components/mocks/mock-data.ts
  apps/web/components/pages/home.tsx
  apps/web/components/sections/achievements/achievement-grid.tsx
  apps/web/components/sections/home/community.tsx
  apps/web/components/sections/home/final-cta.tsx
  apps/web/components/sections/home/hero.tsx
  apps/web/components/sections/home/highlighted-projects.tsx
  apps/web/components/sections/home/how-it-works.tsx
  apps/web/components/sections/home/join-us.tsx
  apps/web/components/sections/home/platform-overview.tsx
  apps/web/components/sections/home/user-journey.tsx
  apps/web/components/sections/project/about-project.tsx
  apps/web/components/sections/project/impact-cards.tsx
  apps/web/components/sections/project/media-player.tsx
  apps/web/components/sections/project/project-overview.tsx
  apps/web/components/sections/project/project-showcase.tsx
  apps/web/components/sections/project/project-updates.tsx
  apps/web/components/sections/project/success-gallery.tsx
  apps/web/components/sections/project/supporter-updates.tsx
  apps/web/components/sections/project/timeline.tsx
  apps/web/components/shared/investment-model-card.tsx
  apps/web/components/shared/project-card-variants.tsx
  apps/web/components/shared/web3-feature-card.tsx
  apps/web/lib/constants/animations.ts
  apps/web/lib/constants/mock-data/mock-projects.ts
  apps/web/lib/mock-data/mock-community-section.tsx
  apps/web/lib/mock-data/mock-final-cta-section.tsx
  apps/web/lib/mock-data/mock-hero-section.tsx
  apps/web/lib/mock-data/mock-how-it-works-section.tsx
  apps/web/lib/mock-data/mock-join-us-section.tsx
  apps/web/lib/mock-data/mock-platform-overview.tsx
  apps/web/lib/mock-data/mock-projects.ts
  apps/web/lib/mock-data/mock-user-journey.tsx
  apps/web/lib/types/home.types.ts
  bun.lock
Labels: documentation, enhancement, chore

#94 Remove Duplicated Layout #78
  apps/web/app/(api-routes)/foo/route.ts
  apps/web/app/(auth-pages)/forgot-password/page.tsx
  apps/web/app/(auth-pages)/sign-in/page.tsx
  apps/web/app/(auth-pages)/sign-up/page.tsx
  apps/web/app/(routes)/dashboard/page.tsx
  apps/web/app/(routes)/home/page.tsx
  apps/web/app/(routes)/project/page.tsx
  apps/web/app/layout.tsx
  apps/web/components/base/carousel.tsx
  apps/web/components/base/image.tsx
  apps/web/components/base/input.tsx
  apps/web/components/base/navigation-menu.tsx
  apps/web/components/base/sidebar.tsx
  apps/web/components/mocks/mock-data.ts
  apps/web/components/sections/achievements/achievement-grid.tsx
  apps/web/components/sections/home/community.tsx
  apps/web/components/sections/home/hero.tsx
  apps/web/components/sections/home/how-it-works.tsx
  apps/web/components/sections/home/join-us.tsx
  apps/web/components/sections/home/new-user-guide.tsx
  apps/web/components/sections/home/platform-overview.tsx
  apps/web/components/sections/home/user-journey.tsx
  apps/web/components/sections/project/about-project.tsx
  apps/web/components/sections/project/impact-cards.tsx
  apps/web/components/sections/project/media-player.tsx
  apps/web/components/sections/project/project-overview.tsx
  apps/web/components/sections/project/project-showcase.tsx
  apps/web/components/sections/project/project-updates.tsx
  apps/web/components/sections/project/success-gallery.tsx
  apps/web/components/sections/project/supporter-updates.tsx
  apps/web/components/sections/project/your-impact.tsx
  apps/web/components/shared/layout/header/header.tsx
  apps/web/components/shared/layout/layout-helpers/root-layout-wrapper.tsx
  apps/web/components/shared/pagination.tsx
  apps/web/components/shared/project-card-variants.tsx
  apps/web/components/shared/steps-card.tsx
  apps/web/components/shared/steps.tsx
  apps/web/components/shared/testimonial-card.tsx
  apps/web/lib/animations.ts
  apps/web/lib/constants/mock-data/mock-projects.ts
  apps/web/lib/mock-data/mock-projects.ts
  apps/web/lib/mock-data/section.ts
  apps/web/lib/types/home.types.ts
  bun.lockb
Labels: documentation, enhancement, webapp, chore

#112 fix: base img render + copilot instructions + biome config tweak
  .github/copilot-instructions.md
  apps/web/components/base/image.tsx
  biome.json
  bun.lockb
Labels: bug, documentation, enhancement, chore

#108 [web]Feat 36 standardize animations
  apps/web/components/base/alert-dialog.tsx
  apps/web/components/base/dialog.tsx
  apps/web/components/base/dropdown-menu.tsx
  apps/web/components/base/sheet.tsx
  apps/web/hooks/use-reduced-motion.tsx
  apps/web/lib/animation.ts
  apps/web/tailwind.config.ts
Labels: documentation, enhancement, webapp

#86 feat: Implement Escrow Initialization API Endpoint #48
  apps/web/.env.sample
  apps/web/app/api/escrow/initialize/route.ts
  apps/web/lib/error.ts
  apps/web/lib/stellar/escrow.ts
  apps/web/lib/types/escrow.ts
  apps/web/lib/utils/id.ts
  apps/web/lib/validators/escrow.ts
Labels: documentation, enhancement, webapp

#110 feat: implement user dashboard and fixes linting errors
  apps/web/components/sections/user/dashboard.tsx
  apps/web/lib/mock-data/mock-user-dashboard.tsx
  apps/web/lib/stellar/escrow.ts
  apps/web/lib/types/user-dashboard.ts
Labels: documentation, enhancement, webapp

#109 feat(web): implement Passkey authentication
  apps/web/app/api/passkey/README.md
  apps/web/app/api/passkey/generate-authentication-options/route.ts
  apps/web/app/api/passkey/generate-registration-options/route.ts
  apps/web/app/api/passkey/verify-authentication/route.ts
  apps/web/app/api/passkey/verify-registration/route.ts
  apps/web/lib/passkey/deploy.ts
  apps/web/lib/passkey/env.ts
  apps/web/lib/passkey/errors.ts
  apps/web/lib/passkey/passkey.ts
  apps/web/lib/passkey/redis.ts
  apps/web/lib/passkey/stellar.ts
  bun.lock
  package.json
Labels: documentation, enhancement, webapp

#118 refactor(types): update type definitions
  apps/web/app/auth/callback/route.ts
  apps/web/components/pages/home.tsx
  apps/web/components/shared/layout/header/navigation.tsx
  apps/web/lib/stellar/escrow.ts
  apps/web/lib/types/home.types.ts
  apps/web/lib/types/index.ts
  apps/web/lib/types/pages.ts
  apps/web/lib/types/project.ts
  apps/web/lib/types/stats.ts
Labels: documentation, enhancement

#122 feat(dashboard): create right panel with user/creator modes and activ…
  apps/web/app/(routes)/dashboard/layout.tsx
  apps/web/components/base/scroll-area.tsx
  apps/web/components/sections/user/right-panel/index.tsx
  apps/web/components/sections/user/right-panel/latest-updates.tsx
  apps/web/components/sections/user/right-panel/lazy-components.tsx
  apps/web/components/sections/user/right-panel/navigation-menu.tsx
  apps/web/components/sections/user/right-panel/recent-activity.tsx
  apps/web/lib/constants/mock-data/right-panel-mocks.ts
  apps/web/lib/services/right-panel-service.ts
  apps/web/lib/types/right-side-panel.ts
  apps/web/package.json
Labels: documentation, enhancement, webapp

#107 fix: improve auth error handling
  apps/web/app/(auth-pages)/sign-in/page.tsx
  apps/web/app/(auth-pages)/sign-up/page.tsx
  apps/web/app/actions.ts
  apps/web/app/auth/callback/route.ts
  apps/web/app/auth/confirm/route.ts
  apps/web/app/layout.tsx
  apps/web/components/base/alert-dialog.tsx
  apps/web/components/base/dialog.tsx
  apps/web/components/base/dropdown-menu.tsx
  apps/web/components/base/sheet.tsx
  apps/web/lib/animation.ts
  apps/web/lib/animations.ts
  apps/web/lib/auth/clientauth-error-handler.ts
  apps/web/lib/auth/error-handler.ts
  apps/web/lib/config/validate-url.ts
  apps/web/lib/constants/animations.ts
  apps/web/lib/constants/error.ts
  apps/web/lib/logger.ts
  apps/web/lib/types/auth/auth.types.ts
  apps/web/lib/types/auth/index.ts
  apps/web/lib/types/logger.types.ts
  bun.lock
Labels: documentation, enhancement, webapp, chore

#117 Feat/implementation of project analysis assistant
  admin/tools/project-analysis/.eslintrc.json
  admin/tools/project-analysis/.gitignore
  admin/tools/project-analysis/README.md
  admin/tools/project-analysis/app/api/chat/route.ts
  admin/tools/project-analysis/app/api/readme/route.ts
  admin/tools/project-analysis/app/favicon.ico
  admin/tools/project-analysis/app/globals.css
  admin/tools/project-analysis/app/layout.tsx
  admin/tools/project-analysis/app/page.tsx
  admin/tools/project-analysis/bun.lock
  admin/tools/project-analysis/next.config.ts
  admin/tools/project-analysis/package-lock.json
  admin/tools/project-analysis/package.json
  admin/tools/project-analysis/postcss.config.mjs
  admin/tools/project-analysis/public/file.svg
  admin/tools/project-analysis/public/globe.svg
  admin/tools/project-analysis/public/next.svg
  admin/tools/project-analysis/public/vercel.svg
  admin/tools/project-analysis/public/window.svg
  admin/tools/project-analysis/tailwind.config.ts
  admin/tools/project-analysis/tsconfig.json
Labels: documentation, enhancement, webapp

#145 chore: consolidate animations.ts file loc
  apps/web/components/base/alert-dialog.tsx
  apps/web/components/base/dialog.tsx
  apps/web/components/base/dropdown-menu.tsx
  apps/web/components/base/sheet.tsx
  apps/web/components/sections/home/hero.tsx
  apps/web/components/sections/home/join-us.tsx
  apps/web/components/sections/home/new-user-guide.tsx
  apps/web/components/sections/home/platform-overview.tsx
  apps/web/lib/animations.ts
  apps/web/lib/constants/animations.ts
Labels: documentation, enhancement, webapp, chore

#151 feat(ui): add Shadcn skeletons for dynamically loaded components
  apps/web/app/css/globals.css
  apps/web/components/base/skeleton-text.tsx
  apps/web/components/base/skeleton.tsx
  apps/web/components/pages/home.tsx
  apps/web/components/sections/home/skeletons.tsx
Labels: documentation, enhancement, webapp

#155 Feat/access control and ownership verification in nft contract
  .cursorrules
  apps/contract/.cargo/config.toml
  apps/contract/Cargo.lock
  apps/contract/Cargo.toml
  apps/contract/contracts/nft/Cargo.toml
  apps/contract/contracts/nft/src/contract.rs
  apps/contract/contracts/nft/src/distribution.rs
  apps/contract/contracts/nft/src/errors.rs
  apps/contract/contracts/nft/src/events.rs
  apps/contract/contracts/nft/src/lib.rs
  apps/contract/contracts/nft/src/storage.rs
  apps/contract/contracts/nft/src/test.rs
  apps/contract/contracts/nft/src/types.rs
  apps/contract/contracts/nft/test_snapshots/test/test_admin_access_control.1.json
  apps/contract/contracts/nft/test_snapshots/test/test_basic_flow.1.json
  apps/contract/contracts/nft/test_snapshots/test/test_error_handling.1.json
  apps/contract/contracts/nft/test_snapshots/test/test_transfer_ownership.1.json
Labels: enhancement, webapp, chore

#158 Feat 18 optimize animations for reduced motion
  apps/contract/README.md
  apps/web/components/base/alert-dialog.tsx
  apps/web/components/base/dropdown-menu.tsx
  apps/web/components/base/sidebar.tsx
  apps/web/lib/animation.ts
Labels: documentation, enhancement, chore

#163 fix: supabase scripts + config project name + readme
  services/supabase/.env.sample
  services/supabase/README.md
  services/supabase/config.toml
  services/supabase/package.json
Labels: bug, documentation, chore

#157 docs: add JSDoc for base UI components
  apps/web/components/base/alert-dialog.tsx
  apps/web/components/base/alert.tsx
  apps/web/components/base/aspect-ratio.tsx
  apps/web/components/base/avatar.tsx
  apps/web/components/base/badge.tsx
  apps/web/components/base/button.tsx
  apps/web/components/base/card.tsx
  apps/web/components/base/carousel.tsx
  apps/web/components/base/checkbox.tsx
  apps/web/components/base/dialog.tsx
  apps/web/components/base/dropdown-menu.tsx
  apps/web/components/base/form.tsx
  apps/web/components/base/input.tsx
  apps/web/components/base/label.tsx
  apps/web/components/base/navigation-menu.tsx
  apps/web/components/base/pagination.tsx
  apps/web/components/base/progress.tsx
  apps/web/components/base/radio-group.tsx
  apps/web/components/base/scroll-area.tsx
  apps/web/components/base/select.tsx
  apps/web/components/base/separator.tsx
  apps/web/components/base/sheet.tsx
  apps/web/components/base/sidebar.tsx
  apps/web/components/base/skeleton.tsx
  apps/web/components/base/sonner.tsx
  apps/web/components/base/switch.tsx
  apps/web/components/base/table.tsx
  apps/web/components/base/tabs.tsx
  apps/web/components/base/textarea.tsx
  apps/web/components/base/tooltip.tsx
Labels: documentation, enhancement

#161 Feat #63 implement escrow system
  apps/web/app/actions.ts
  apps/web/app/escrow/monitor/page.tsx
  apps/web/components/sections/monitor/index.ts
  apps/web/components/sections/monitor/status-table.tsx
  apps/web/hooks/escrow/use-Escrow.ts
  apps/web/lib/config/app.config.ts
  apps/web/lib/utils/escrow.ts
  apps/web/package.json
  bun.lockb
  services/supabase/.gitignore
  services/supabase/database.types.ts
  services/supabase/migrations/20250212130814_create_escrow_status.sql
  services/supabase/src/database.types.ts
  services/supabase/src/index.ts
  services/supabase/types/database.types.ts
Labels: documentation, enhancement, webapp, dev op, chore

#159 chore/setup-trustless-work
  apps/web/app/api/escrow/initialize/route.ts
  apps/web/lib/axios/http.ts
  apps/web/lib/stellar/escrow.ts
  apps/web/lib/stellar/utils/create-escrow.ts
  apps/web/lib/stellar/utils/get-endpoint.ts
  apps/web/lib/stellar/utils/send-transaction.ts
  apps/web/lib/stellar/utils/sign-transaction.ts
  apps/web/lib/supabase/config.ts
  apps/web/lib/types/date.types.ts
  apps/web/lib/types/escrow.types.ts
  apps/web/lib/types/escrow/escrow-endpoint.types.ts
  apps/web/lib/types/escrow/escrow-payload.types.ts
  apps/web/lib/types/escrow/escrow-response.types.ts
  apps/web/lib/types/escrow/escrow.types.ts
  apps/web/lib/types/index.ts
  apps/web/lib/types/utils.types.ts
  apps/web/lib/validators/escrow.ts
  package-lock.json
  package.json
Labels: documentation, enhancement, webapp, chore

#175 fix: bun build
  apps/contract/contracts/nft/test_snapshots/test/test_admin_access_control.1.json
  apps/contract/contracts/nft/test_snapshots/test/test_basic_flow.1.json
  apps/contract/contracts/nft/test_snapshots/test/test_error_handling.1.json
  apps/contract/contracts/nft/test_snapshots/test/test_transfer_ownership.1.json
  apps/web/app/actions.ts
  apps/web/app/escrow/monitor/page.tsx
  apps/web/components/sections/monitor/index.ts
  apps/web/components/sections/monitor/status-table.tsx
  apps/web/components/shared/layout/providers.tsx
  apps/web/hooks/escrow/use-Escrow.ts
  apps/web/hooks/use-escrow.ts
  apps/web/lib/axios/http.ts
  apps/web/lib/config/app.config.ts
  apps/web/lib/stellar/utils/create-escrow.ts
  apps/web/lib/stellar/utils/send-transaction.ts
  apps/web/lib/utils/escrow.ts
  apps/web/package.json
  bun.lockb
  package-lock.json
  services/supabase/.branches/_current_branch
  services/supabase/database.types.ts
  services/supabase/src/index.ts
  services/supabase/types/database.types.ts
Labels: bug, documentation, enhancement, chore

#174 feat(auth): implement rate limiting for OTP verification & lint/format errors
  .husky/pre-commit
  apps/web/.env.sample
  apps/web/app/auth/confirm/route.ts
  apps/web/components/icons/illustrations.tsx
  apps/web/lib/auth/rate-limiter.ts
  apps/web/package.json
  apps/web/test/auth-rate-limit.test.mjs
  apps/web/test/check-redis.test.mjs
Labels: documentation, enhancement, webapp, chore

#162 feat: Create escrow_contracts table for escrow contract tracking
  services/supabase/migrations/20250216144527_create_escrow_contract_table.sql
  services/supabase/src/database.schemas.ts
  services/supabase/src/database.types.ts
Labels: bug, documentation, enhancement, webapp, dev op, chore

#173 Feat project table schema
  .husky/pre-commit
  apps/web/hooks/escrow/use-Escrow.ts
  services/supabase/.env.sample
  services/supabase/config.toml
  services/supabase/migrations/20250212015319_create_project_schema.sql
  services/supabase/migrations/20250216144527_create_escrow_contract_table.sql
  services/supabase/package.json
  services/supabase/schema_docs/create_project_schema.md
  services/supabase/src/database.schemas.ts
  services/supabase/src/database.types.ts
Labels: bug, documentation, enhancement, webapp, chore

#198 feat: create project form
  apps/web/app/create-project/page.tsx
  apps/web/components/sections/project/project-form.tsx
  apps/web/components/shared/layout/header/navigation.tsx
  apps/web/hooks/use-multi-step-form.ts
  apps/web/lib/validators/project.ts
Labels: documentation, enhancement, webapp

#197 [FEAT]: Create "Featured Creators" Components
  apps/web/components/sections/featured-creators/featured-creators.tsx
  apps/web/components/sections/featured-creators/skeletons.tsx
  apps/web/components/shared/feature-creator-card.tsx
Labels: documentation, enhancement, webapp

#200 feat: enhance image upload handling with size limits and error feedback
  apps/web/components/sections/project/project-form.tsx
  apps/web/hooks/use-multi-step-form.ts
  apps/web/lib/validators/project.ts
  bun.lockb
Labels: documentation, enhancement, webapp

#201 Feat: Built Proof of Address Upload Component
  apps/web/components/base/toast.tsx
  apps/web/components/pages/home.tsx
  apps/web/components/shared/kyc-4-upload.tsx
  apps/web/components/types/types.ts
  apps/web/package.json
Labels: documentation, enhancement, webapp, chore

#202 feat: create learning section
  apps/web/app/(routes)/learn/page.tsx
  apps/web/components/cards/category-card.tsx
  apps/web/components/cards/news-card.tsx
  apps/web/components/cards/resource-card.tsx
  apps/web/components/sections/learning/category-grid.tsx
  apps/web/components/sections/learning/hero-badge.tsx
  apps/web/components/sections/learning/hero-buttons.tsx
  apps/web/components/sections/learning/hero.tsx
  apps/web/components/sections/learning/join-community.tsx
  apps/web/components/sections/learning/latest-updates.tsx
  apps/web/components/sections/learning/level-tabs.tsx
  apps/web/components/sections/learning/news-grid.tsx
  apps/web/components/sections/learning/resource-filters.tsx
  apps/web/components/sections/learning/resource-grid.tsx
  apps/web/components/sections/learning/search-bar.tsx
  apps/web/components/sections/learning/section-header.tsx
  apps/web/components/sections/learning/update-card.tsx
  apps/web/lib/constants/mock-data/mock-learning.ts
  apps/web/lib/types/learning.types.ts
  apps/web/lib/utils/date-utils.ts
  bun.lockb
  package.json
Labels: documentation, enhancement, webapp, chore

#178 Add escrow payment handling
  apps/web/.env.sample
  apps/web/app/api/escrow/fund/[transactionHash]/route.ts
  apps/web/app/api/escrow/fund/route.ts
  apps/web/components/base/toast.tsx
  apps/web/components/pages/home.tsx
  apps/web/components/shared/kyc-4-upload.tsx
  apps/web/components/types/types.ts
  apps/web/hooks/use-escrow-funding.tsx
  apps/web/lib/passkey/deploy.ts
  apps/web/lib/stellar/utils/sign-transaction.ts
  apps/web/lib/types/escrow/escrow-payload.types.ts
  apps/web/lib/types/escrow/escrow-response.types.ts
  apps/web/lib/validators/escrow.ts
  apps/web/package.json
  bun.lockb
  package.json
Labels: bug, documentation, enhancement, webapp, TL, Backend

#206 Feat/recent social impacts section
  apps/web/app/(routes)/impact/page.tsx
  apps/web/components/base/badge-impact.tsx
  apps/web/components/base/category-card.tsx
  apps/web/components/base/impact-maker-card.tsx
  apps/web/components/base/link.tsx
  apps/web/components/pages/impact.tsx
  apps/web/components/sections/impact/categories.tsx
  apps/web/components/sections/impact/get-involved.tsx
  apps/web/components/sections/impact/hero.tsx
  apps/web/components/sections/impact/impact-makers.tsx
  apps/web/components/sections/impact/skeletons.tsx
  apps/web/components/sections/impact/success-stories.tsx
  apps/web/components/sections/impact/testimonials.tsx
  apps/web/components/shared/impact-maker.tsx
  apps/web/components/shared/story-card.tsx
  apps/web/components/shared/testimonial-card-impact.tsx
  apps/web/lib/constants/animations.ts
  apps/web/lib/constants/impact-data/hero-data.ts
  apps/web/lib/constants/impact-data/impact-categories.ts
  apps/web/lib/constants/impact-data/makers.ts
  apps/web/lib/constants/impact-data/succes-data.ts
  apps/web/lib/constants/impact-data/testimonials-data.ts
  apps/web/lib/types/impact/hero.ts
  apps/web/lib/types/impact/impact-categories.ts
  apps/web/lib/types/impact/impact-makers.ts
  apps/web/lib/types/impact/succes-story.ts
  apps/web/lib/types/impact/testimonial.ts
  bun.lockb
Labels: documentation, enhancement, webapp

#170 feat: dynamic project tags UI and color generation system #136
  apps/web/app/(routes)/project/create/page.tsx
  apps/web/components/shared/tag-edit.tsx
  apps/web/components/shared/tag-manager.tsx
  apps/web/lib/mock-data/mock-projects.ts
  apps/web/lib/types/project.types.ts
  apps/web/lib/utils/tag-context.ts
  apps/web/lib/utils/types-helpers.ts
Labels: documentation, enhancement, webapp

#211 [web] Feat: Create 'Project Highlights' view
  apps/web/app/(routes)/project/[id]/highlights/page.tsx
  apps/web/components/sections/project/highlights/example-highlight-card.tsx
  apps/web/components/sections/project/highlights/example-highlights.tsx
  apps/web/components/sections/project/highlights/project-highlight-card.tsx
  apps/web/components/sections/project/highlights/writing-tips.tsx
  apps/web/lib/utils/id.ts
Labels: documentation, enhancement, webapp

#207 kyc-2 UI design has been created
  apps/web/components/shared/kyc/kyc-2/document-type-selector.tsx
  apps/web/components/shared/kyc/kyc-2/document-upload-zone.tsx
  apps/web/components/shared/kyc/kyc-2/extracted-data-display.tsx
  apps/web/components/shared/kyc/kyc-2/kyc-2-upload.tsx
  apps/web/components/shared/kyc/kyc-2/types.ts
  apps/web/components/shared/kyc/kyc-2/validation-alerts.tsx
  apps/web/components/shared/kyc/kyc-4/kyc-4-upload.tsx
  apps/web/hooks/kyc/use-document-files.ts
  apps/web/hooks/kyc/use-document-processor.ts
  apps/web/hooks/kyc/use-document-validation.ts
  apps/web/package.json
  apps/web/styles/globals.css
  bun.lockb
Labels: documentation, enhancement, webapp, TL, Backend

#217 Refactored sidebar transitions for better performance
  apps/web/components/base/sidebar.tsx
  bun.lockb
Labels: documentation, enhancement, webapp

#209 Feat/edit project basics
  .gitignore
  apps/web/app/(auth-pages)/forgot-password/page.tsx
  apps/web/app/(auth-pages)/reset-password/page.tsx
  apps/web/app/edit-project/page.tsx
  apps/web/components/base/input.tsx
  apps/web/components/base/select.tsx
  apps/web/components/base/textarea.tsx
  apps/web/components/sections/faqs/faq-header.tsx
  apps/web/components/sections/project/edit-project.tsx
  apps/web/components/shared/kyc/kyc-2/kyc-2-upload.tsx
  apps/web/components/shared/tag-edit.tsx
  apps/web/components/shared/tag-manager.tsx
  apps/web/hooks/kyc/use-document-validation.ts
  apps/web/hooks/use-file-upload.ts
  apps/web/lib/utils/upload-file-to-bucket.ts
  apps/web/lib/validators/project.ts
  apps/web/package.json
  bun.lock
  bun.lockb
Labels: documentation, enhancement, webapp, chore, TL, Backend

#213 feat: implement fe kyc step 5 - final review & submission
  apps/web/components/shared/kyc/kyc-5/final-review.tsx
  apps/web/components/shared/kyc/kyc-5/review-section.tsx
  apps/web/lib/mock-data/mock-step5-keydata.ts
  apps/web/lib/types/final-review-kyc5.types.ts
Labels: documentation, enhancement, webapp, TL, Backend

#230 Add Proof of Face Verification Component
  apps/web/components/sections/faqs/faq-header.tsx
  apps/web/components/shared/kyc/kyc-3/kyc-3.tsx
  apps/web/components/shared/kyc/kyc-3/types.ts
  bun.lock
  package.json
Labels: documentation, enhancement, webapp, Backend

#231 Feature/enhance project categories Styling with Dedicated CSS
  apps/web/app/(auth-pages)/reset-password/page.tsx
  apps/web/app/css/categories.css
  apps/web/app/css/globals.css
  apps/web/components/category/categoryTag/CategoryTag.tsx
  apps/web/components/sections/project/project-form.tsx
  apps/web/components/shared/kyc/kyc-5/final-review.tsx
  apps/web/lib/constants/project.constants.ts
  apps/web/lib/types/final-review-kyc5.types.ts
  apps/web/lib/types/projects.types.ts
Labels: documentation, enhancement, webapp, chore

#228 feat: create about us section
  apps/web/app/(routes)/about/page.tsx
  apps/web/components/base/icon.tsx
  apps/web/components/sections/about-us/call-to-action.tsx
  apps/web/components/sections/about-us/hero.tsx
  apps/web/components/sections/about-us/how-it-works.tsx
  apps/web/components/sections/about-us/kindfi-stellar.tsx
  apps/web/components/sections/about-us/mission-vision.tsx
  apps/web/components/sections/about-us/problems.tsx
  apps/web/components/sections/about-us/roadmap.tsx
  apps/web/components/sections/about-us/why-is-different.tsx
  apps/web/components/shared/floating-feature.tsx
  apps/web/components/shared/timeline-step.tsx
  apps/web/components/shared/timeline.tsx
  apps/web/lib/mock-data/mock-about-us.ts
  apps/web/package.json
Labels: documentation, enhancement, webapp, TL

#223 Feat/top investors section
  apps/web/app/(routes)/community/page.tsx
  apps/web/components/base/icon.tsx
  apps/web/components/pages/kindlers.tsx
  apps/web/components/sections/community/become-top-investor.tsx
  apps/web/components/sections/community/category-select.tsx
  apps/web/components/sections/community/hero.tsx
  apps/web/components/sections/community/investor-card.tsx
  apps/web/components/sections/community/investor-grid.tsx
  apps/web/components/sections/community/no-results-message.tsx
  apps/web/components/sections/community/sort-select.tsx
  apps/web/components/sections/community/top-investors.tsx
  apps/web/components/sections/faqs/faq-header.tsx
  apps/web/components/shared/floating-feature.tsx
  apps/web/components/shared/timeline-step.tsx
  apps/web/components/shared/timeline.tsx
  apps/web/hooks/use-filtered-and-sorted-investors.ts
  apps/web/lib/constants/animations.ts
  apps/web/lib/constants/mock-data/community-hero-data.ts
  apps/web/lib/constants/mock-data/community-top-investors-data.ts
  apps/web/lib/mock-data/mock-about-us.ts
  apps/web/lib/types/investors/hero.ts
  apps/web/lib/types/investors/top-investors.ts
  apps/web/lib/utils/safe-parse-float.ts
Labels: documentation, enhancement, webapp, chore, TL

#221 [web] Feat: Create "Complete Your Pitch" View
  apps/web/app/(routes)/project/[id]/pitch/page.tsx
  apps/web/components/sections/faqs/faq-header.tsx
  apps/web/components/sections/project/pitch/hero.tsx
  apps/web/components/sections/project/pitch/tips-sidebar.tsx
  apps/web/components/sections/project/pitch/upcoming-steps.tsx
  apps/web/lib/constants/animations.ts
  apps/web/lib/mock-data/project/mock-pitch.ts
  apps/web/lib/types/project/pitch.types.ts
Labels: documentation, enhancement, webapp, chore, TL

#220 Feat/pitch and story view
  apps/web/app/(routes)/project/[id]/story/page.tsx
  apps/web/components/base/input.tsx
  apps/web/components/sections/project/project-media.tsx
  apps/web/components/sections/project/project-story.tsx
  apps/web/components/sections/project/project-tips.tsx
  apps/web/components/sections/project/rich-text-editor.tsx
  apps/web/lib/validators/project.ts
  apps/web/package.json
Labels: documentation, enhancement, webapp, TL

#219 Feat: Create projects Section
  apps/web/app/(routes)/projects/layout.tsx
  apps/web/app/(routes)/projects/page.tsx
  apps/web/components/sections/projects/category-filter.tsx
  apps/web/components/sections/projects/index.ts
  apps/web/components/sections/projects/projects-grid.tsx
  apps/web/components/sections/projects/projects-header.tsx
  apps/web/components/sections/projects/sort-dropdown.tsx
  apps/web/hooks/use-projects-filter.ts
  apps/web/lib/mock-data/mock-projects-view.tsx
  apps/web/lib/types/projects.types.ts
  apps/web/public/icons/climate.svg
  apps/web/public/icons/community.svg
  apps/web/public/icons/education.svg
  apps/web/public/icons/energy.svg
  apps/web/public/icons/food.svg
  apps/web/public/icons/healthcare.svg
  apps/web/public/icons/relief.svg
  apps/web/public/icons/social.svg
  apps/web/public/icons/sustainability.svg
  apps/web/public/icons/water.svg
Labels: documentation, enhancement, webapp, chore, TL

#236 feat/Add Security Headers to API Responses
  apps/web/next.config.ts
Labels: webapp, Backend

#244 Refactor 234 relative imports
  apps/web/app/(routes)/project/create/page.tsx
  apps/web/components/sections/project/project-form.tsx
  apps/web/components/sections/project/project-media.tsx
  apps/web/components/sections/project/project-story.tsx
  apps/web/components/sections/project/project-tips.tsx
  apps/web/components/sections/project/rich-text-editor.tsx
  apps/web/components/shared/kyc/kyc-2/kyc-2-upload.tsx
  apps/web/components/shared/tag-edit.tsx
  apps/web/components/shared/tag-manager.tsx
  apps/web/hooks/kyc/use-document-files.ts
  apps/web/hooks/kyc/use-document-processor.ts
  apps/web/hooks/kyc/use-document-validation.ts
  services/ai/tests/services/ai.test.ts
  tsconfig.json
Labels: enhancement, webapp, chore

#241 Added checks and docs for service role key
  apps/web/lib/supabase/check-env-vars.ts
  services/supabase/README.md
  services/supabase/Screenshot from 2025-02-27 17-59-15.png
Labels: bug, documentation

#247 Enhance rich text editor link interface with a custom dialog component #222
  apps/web/components/header-auth.tsx
  apps/web/components/sections/project/LinkDialog.tsx
  apps/web/components/sections/project/rich-text-editor.tsx
  apps/web/lib/supabase/check-env-vars.ts
Labels: enhancement, feature, webapp, Frontend

#246 feat: add upload status and file preview to ProjectMedia component
  apps/web/app/(routes)/project/[id]/story/page.tsx
  apps/web/components/sections/project/project-media.tsx
Labels: documentation, enhancement, webapp, chore, Frontend

#245 Refactor 232 project form component
  apps/web/app/create-project/page.tsx
  apps/web/components/sections/project/project-form.tsx
  apps/web/components/sections/project/project-form/additional-details-step.tsx
  apps/web/components/sections/project/project-form/funding-information-step.tsx
  apps/web/components/sections/project/project-form/index.tsx
  apps/web/components/sections/project/project-form/project-details-step.tsx
  services/supabase/README.md
  services/supabase/Screenshot from 2025-02-27 17-59-15.png
Labels: enhancement, webapp, Frontend

#249 Feat/kyc-1
  apps/web/app/kyc/page.tsx
  apps/web/components/base/calendar.tsx
  apps/web/components/base/popover.tsx
  apps/web/components/shared/kyc/kyc-1/date-of-birth-field.tsx
  apps/web/components/shared/kyc/kyc-1/full-name-field.tsx
  apps/web/components/shared/kyc/kyc-1/identity-verification.tsx
  apps/web/components/shared/kyc/kyc-1/index.tsx
  apps/web/components/shared/kyc/kyc-1/nationality-field.tsx
  apps/web/components/shared/kyc/kyc-1/progress-indicator.tsx
  apps/web/components/shared/kyc/kyc-1/types.tsx
  apps/web/components/shared/kyc/kyc-modal.tsx
  apps/web/package.json
  bun.lock
  package.json
Labels: documentation, enhancement, webapp, Frontend, TL, Backend

#242 Feature/refactor project card components to follow dry principles #238
  apps/web/components/base/progress.tsx
  apps/web/components/featured/project-card.tsx
  apps/web/components/featured/projects-grid.tsx
  apps/web/components/sections/home/highlighted-projects.tsx
  apps/web/components/sections/projects/projects-grid.tsx
  apps/web/components/sections/user/dashboard.tsx
  apps/web/components/shared/project-card.tsx
  apps/web/hooks/use-projects-filter.ts
  apps/web/lib/mock-data/featured-projects/mock-featured-projets.ts
  apps/web/lib/mock-data/mock-projects-view.tsx
  apps/web/lib/types/featured-projects/featured-projects.types.ts
  apps/web/lib/types/projects.types.ts
  apps/web/lib/types/user-dashboard.types.ts
Labels: documentation, enhancement, webapp, chore, TL
