Repository kindfi-org/kindfi, pull requests merged in 2025-03, with the labels that each got.

#254 feat: Refactor: Express.js to Bun native server with React SSR Integration
  apps/kyc-server/.env-sample
  apps/kyc-server/.env.example
  apps/kyc-server/.gitignore
  apps/kyc-server/README.md
  apps/kyc-server/build.ts
  apps/kyc-server/docs/BUILD.md
  apps/kyc-server/docs/CORS.md
  apps/kyc-server/docs/ROUTING.md
  apps/kyc-server/docs/SUMMARY.md
  apps/kyc-server/package.json
  apps/kyc-server/public/client-m7pwck9zpft.js
  apps/kyc-server/public/index.html
  apps/kyc-server/public/manifest.json
  apps/kyc-server/public/styles.css
  apps/kyc-server/src/app.ts
  apps/kyc-server/src/client.tsx
  apps/kyc-server/src/components/About.tsx
  apps/kyc-server/src/components/App.tsx
  apps/kyc-server/src/components/Home.tsx
  apps/kyc-server/src/components/Navigation.tsx
  apps/kyc-server/src/components/WebSocketDemo.tsx
  apps/kyc-server/src/config/cors.ts
  apps/kyc-server/src/controllers/index.ts
  apps/kyc-server/src/db/schema.ts
  apps/kyc-server/src/index.tsx
  apps/kyc-server/src/middleware/cors.ts
  apps/kyc-server/src/resolvers/index.ts
  apps/kyc-server/src/routes/index.ts
  apps/kyc-server/src/routes/ping.ts
  apps/kyc-server/src/routes/react.tsx
  apps/kyc-server/src/types/apollo-resolvers.ts
  apps/kyc-server/src/types/index.ts
  apps/kyc-server/src/utils/buildClient.ts
  apps/kyc-server/src/utils/contentMap.tsx
  apps/kyc-server/src/utils/error-handler.ts
  apps/kyc-server/tsconfig.json
  apps/web/components/featured/projects-grid.tsx
  apps/web/components/sections/projects/projects-grid.tsx
  apps/web/components/shared/project-card.tsx
  apps/web/hooks/use-projects-filter.ts
  apps/web/lib/mock-data/featured-projects/mock-featured-projets.ts
  apps/web/lib/mock-data/mock-projects-view.tsx
  apps/web/lib/types/featured-projects/featured-projects.types.ts
  apps/web/lib/types/projects.types.ts
  apps/web/lib/types/user-dashboard.types.ts
  biome.json
  bun.lock
Labels: enhancement, difficulty: hard, feature, webapp, chore, TL

#257 feat: Create project_pitch table
  services/supabase/migrations/20250228212011_create_project_pitch_table.sql
Labels: enhancement, webapp

#261 feat: Broke down TeamMembersPage into smaller reusable components
  apps/kyc-server/src/routes/index.ts
  apps/web/app/team-members/page.tsx
  apps/web/components/pages/team-members/components/ImageUploader.tsx
  apps/web/components/pages/team-members/components/TeamMemberCard.tsx
  apps/web/components/pages/team-members/components/TeamMemberForm.tsx
  apps/web/components/pages/team-members/components/TeamMemberList.tsx
  apps/web/components/pages/team-members/components/VisibilityToggle.tsx
  apps/web/components/pages/team-members/team-members.tsx
Labels: documentation, enhancement, webapp, chore, Frontend, TL

#263 Fix public.project_pitch RLS policies and updates
  services/supabase/migrations/20250228212011_create_project_pitch_table.sql
Labels: bug, enhancement, webapp

#258 Feat 137 project tags schema
  apps/kyc-server/docs/SUMMARY.md
  apps/web/app/api/tag/[tagId]/route.ts
  apps/web/app/api/tag/route.ts
  services/supabase/migrations/20250302053608_create_project_tags.sql
Labels: bug, enhancement, feature, webapp, documentation

#265 feat: Implement User Relationships Kinders and Kindlers
  services/supabase/migrations/20250220114056_create_user_relationships.sql
  services/supabase/migrations/20250220114242_create_rls_policies.sql
Labels: enhancement, webapp, documentation

#266 Doc: Component Usage Example
  docs/component-usage-example.md
Labels: webapp, Frontend

#262 feat: added escrow_milestones table in db schema
  services/supabase/migrations/20250303172116_add_escrow_milestones_table_and_others.sql
  services/supabase/src/database.schemas.ts
  services/supabase/src/database.types.ts
Labels: enhancement, webapp, supabase, dev op

#218 chore: modularized the kyc upload for document validation
  apps/web/components/shared/kyc/kyc-4/document-preview.tsx
  apps/web/components/shared/kyc/kyc-4/document-type-selector.tsx
  apps/web/components/shared/kyc/kyc-4/extracted-info-display.tsx
  apps/web/components/shared/kyc/kyc-4/file-upload-area.tsx
  apps/web/components/shared/kyc/kyc-4/kyc-4-upload.tsx
  apps/web/components/shared/kyc/kyc-4/ocr-processor.tsx
  apps/web/components/shared/kyc/kyc-4/validation-display.tsx
  apps/web/package.json
  bun.lock
  packages/lib/package.json
  packages/lib/src/doc-utils/extraction.ts
  packages/lib/src/doc-utils/file-processing.ts
  packages/lib/src/doc-utils/index.ts
  packages/lib/src/doc-utils/types.ts
  packages/lib/src/doc-utils/validation.ts
  packages/lib/src/index.ts
Labels: enhancement, webapp, chore, Frontend, TL, Backend

#277 Refactor 251 form components to use shadcn UI components
  apps/web/app/css/globals.css
  apps/web/components/sections/project/project-form/additional-details-step.tsx
  apps/web/components/sections/project/project-form/funding-information-step.tsx
  apps/web/components/sections/project/project-form/header-project-form.tsx
  apps/web/components/sections/project/project-form/index.tsx
  apps/web/components/sections/project/project-form/project-details-step.tsx
  apps/web/components/sections/project/project-form/step-indicator.tsx
Labels: enhancement, webapp, chore, TL, documentation

#279 JSDocs Last Review: Enrich UI Docs, Adjust Exports and Imports
  apps/web/components/base/accordion.tsx
  apps/web/components/base/calendar.tsx
  apps/web/components/base/popover.tsx
  apps/web/components/base/toast.tsx
  apps/web/components/shared/kyc/kyc-4/document-preview.tsx
  apps/web/components/shared/kyc/kyc-4/kyc-4-upload.tsx
  packages/lib/src/doc-utils/validation.ts
Labels: enhancement, webapp, chore, Frontend, documentation

#239 wip: feat(api): add milestone review payload and validation
  apps/web/app/api/escrow/review/route.ts
  apps/web/lib/types/escrow/escrow-payload.types.ts
  apps/web/lib/validators/escrow.ts
  docs/component-usage-example.md
Labels: enhancement, feature, webapp, supabase, TL, backend

#300 [web] Feat: Create the Overview Section
  apps/web/components/sections/project/overview/featured-update.tsx
  apps/web/components/sections/project/overview/financial-summary.tsx
  apps/web/components/sections/project/overview/investment-terms.tsx
  apps/web/components/sections/project/overview/key-highlights.tsx
  apps/web/components/sections/project/overview/lead-investors.tsx
  apps/web/components/sections/project/overview/overview-section.tsx
  apps/web/lib/mock-data/project/mock-overview-section.tsx
  apps/web/lib/types/project/overview-section.types.ts
Labels: enhancement, difficulty: medium, feature, webapp, frontend, TL, ODHack12

#301 feat: add academy app
  apps/academy-wep/.env.sample
  apps/academy-wep/.eslintrc.json
  apps/academy-wep/.gitignore
  apps/academy-wep/README.md
  apps/academy-wep/app/favicon.ico
  apps/academy-wep/app/globals.css
  apps/academy-wep/app/layout.tsx
  apps/academy-wep/app/page.tsx
  apps/academy-wep/components.json
  apps/academy-wep/components/ui/button.tsx
  apps/academy-wep/components/ui/input.tsx
  apps/academy-wep/eslint.config.mjs
  apps/academy-wep/lib/utils.ts
  apps/academy-wep/next.config.ts
  apps/academy-wep/package.json
  apps/academy-wep/postcss.config.mjs
  apps/academy-wep/tailwind.config.ts
  apps/academy-wep/tsconfig.json
  apps/web/app/api/escrow/review/route.ts
  bun.lock
Labels: enhancement, difficulty: hard, feature, webapp, TL, documentation

#328 Feat/project details tab
  apps/web/app/(routes)/project/[id]/page.tsx
  apps/web/app/(routes)/project/create/highlights/page.tsx
  apps/web/app/(routes)/project/create/pitch/page.tsx
  apps/web/app/(routes)/project/create/story/page.tsx
  apps/web/app/(routes)/projects/page.tsx
  apps/web/components/pages/project-details/project-details.tsx
  apps/web/components/sections/projects/BusinessModel.tsx
  apps/web/components/sections/projects/CompetitiveAdvantages.tsx
  apps/web/components/sections/projects/InvestmentDetails.tsx
  apps/web/components/sections/projects/MarketOpportunity.tsx
  apps/web/components/sections/projects/ProjectDocuments.tsx
  apps/web/components/sections/projects/ProjectOverview.tsx
  apps/web/components/sections/projects/Technology.tsx
  apps/web/components/sections/projects/TractionMilestones.tsx
  apps/web/lib/mock-data/mock-business-model.ts
  apps/web/lib/mock-data/mock-competitive-adventage.ts
  apps/web/lib/mock-data/mock-investment-details.tsx
  apps/web/lib/mock-data/mock-market-opportunity.ts
  apps/web/lib/mock-data/mock-project-documents.ts
  apps/web/lib/mock-data/mock-project-overview.ts
  apps/web/lib/mock-data/mock-technology.ts
  apps/web/lib/mock-data/mock-traction-milestones.ts
  bun.lock
Labels: enhancement, feature, webapp, frontend

#343 Implement Passkey-login and register UI #321
  apps/web/app/(auth-pages)/sign-in/page.tsx
  apps/web/app/(auth-pages)/sign-up/page.tsx
  apps/web/components/base/dialog.tsx
  apps/web/components/shared/passkey-info-dialog.tsx
Labels: enhancement, feature, webapp, frontend

#326 Create the Project Details- Team Tab Section
  apps/web/app/(routes)/project/[projectId]/not-found.tsx
  apps/web/app/(routes)/project/[projectId]/page.tsx
  apps/web/app/(routes)/project/create/team-members/page.tsx
  apps/web/app/(routes)/projects/page.tsx
  apps/web/components/pages/project/project-information/project-detail-view.tsx
  apps/web/components/sections/project/teams/advisory-board.tsx
  apps/web/components/sections/project/teams/leadership-team.tsx
  apps/web/components/sections/project/teams/teams-tab.tsx
  apps/web/components/shared/project-card.tsx
  apps/web/lib/mock-data/project/teams.ts
  apps/web/lib/types/project/team.ts
  apps/web/public/images/placeholder.png
Labels: enhancement, feature, webapp, frontend

#332 feat: create newsletter subscription component
  apps/academy-wep/components/newsletter-subscription.tsx
Labels: feature, webapp, frontend, ODHack12, May Be Rewarded, academy

#333 Feat/knowledge resources section
  apps/academy-wep/components/knowledge-resources/featured-resources.tsx
  apps/academy-wep/components/knowledge-resources/knowledge-resources.tsx
  apps/academy-wep/components/knowledge-resources/resource-card.tsx
  apps/academy-wep/components/knowledge-resources/search-bar.tsx
  apps/academy-wep/lib/knowledge-resources.ts
Labels: enhancement, difficulty: medium, feature, webapp, frontend, ODHack12, academy

#342 Built OTP Input Accessibility with ARIA Enhancements
  apps/web/app/(auth-pages)/otp-validation/page.tsx
  apps/web/components/base/input-otp.tsx
  apps/web/components/shared/otp-tips.tsx
  apps/web/package.json
Labels: enhancement, webapp, frontend, documentation

#339 feat: create hero main component
  apps/academy-wep/app/constants/colors.ts
  apps/academy-wep/app/page.tsx
  apps/academy-wep/components/credential-card.tsx
  apps/academy-wep/components/hero-section.tsx
  apps/academy-wep/package.json
  bun.lock
Labels: feature, webapp, frontend

#350 Feat: improve current components - button shadcn based
  apps/web/components/base/button.tsx
Labels: enhancement, feature, frontend

#341 feature-learning-paths
  apps/academy-wep/app/page.tsx
  apps/academy-wep/components.json
  apps/academy-wep/components/ui/Card.tsx
  apps/academy-wep/components/ui/button.tsx
  apps/academy-wep/components/ui/cta-button.tsx
  apps/academy-wep/components/ui/featured-learning-paths.tsx
  apps/academy-wep/components/ui/icon.tsx
  apps/academy-wep/components/ui/input.tsx
  apps/academy-wep/components/ui/learning-path-card.tsx
  apps/academy-wep/components/ui/stats-display.tsx
  apps/academy-wep/package.json
  apps/academy-wep/tsconfig.json
  bun.lock
Labels: feature, webapp, frontend, ODHack12, May Be Rewarded, academy

#338 feat:built the why-choose section
  apps/academy-wep/app/page.tsx
  apps/academy-wep/components.json
  apps/academy-wep/components/credential-card.tsx
  apps/academy-wep/components/hero-section.tsx
  apps/academy-wep/components/newsletter-subscription.tsx
  apps/academy-wep/components/sections/feature-card.tsx
  apps/academy-wep/components/sections/why-choose.tsx
  apps/academy-wep/components/ui/button.tsx
  apps/academy-wep/components/ui/card.tsx
  apps/academy-wep/components/ui/cta-button.tsx
  apps/academy-wep/components/ui/featured-learning-paths.tsx
  apps/academy-wep/components/ui/icon.tsx
  apps/academy-wep/components/ui/learning-path-card.tsx
  apps/academy-wep/components/ui/stats-display.tsx
  apps/academy-wep/hooks/use-element-visibility.ts
  apps/academy-wep/hooks/use-reduced-motion.ts
  apps/academy-wep/tsconfig.json
  apps/web/app/(auth-pages)/sign-in/page.tsx
  apps/web/app/(auth-pages)/sign-up/page.tsx
  apps/web/components/base/button.tsx
  apps/web/components/base/dialog.tsx
  apps/web/components/base/input-otp.tsx
  apps/web/components/pages/home.tsx
  apps/web/components/shared/passkey-info-dialog.tsx
  apps/web/lib/constants/theme-color.contants.ts
  bun.lock
  package.json
Labels: feature, webapp, frontend, ODHack12, May Be Rewarded

#347 Feat nft achievement collection
  apps/academy-wep/components/Achivement.tsx
  apps/academy-wep/components/page/achivement.tsx
  apps/academy-wep/components/shared/achivement-card.tsx
  apps/academy-wep/data/achivement-data.ts
  apps/web/app/page.tsx
  bun.lock
Labels: enhancement, webapp

#355 Enhance pre-commit with Supabase check, update components and DB types
  .husky/pre-commit
  apps/academy-wep/components/Achivement.tsx
  apps/academy-wep/components/page/achivement.tsx
  apps/academy-wep/components/shared/achivement-card.tsx
  apps/academy-wep/components/ui/Card.tsx
  apps/academy-wep/data/achivement-data.ts
  apps/web/app/page.tsx
  services/supabase/src/database.schemas.ts
  services/supabase/src/database.types.ts
  services/supabase/types/database.types.ts
Labels: enhancement, devops, chore, backend, dev op

#364 [academy-web] Feat: Create the KindFi Academy Layout Navigation Sidebar and Footer
  apps/academy-wep/app/globals.css
  apps/academy-wep/app/layout.tsx
  apps/academy-wep/app/page.tsx
  apps/academy-wep/components/base/badge.tsx
  apps/academy-wep/components/base/button.tsx
  apps/academy-wep/components/base/card.tsx
  apps/academy-wep/components/base/collapsible.tsx
  apps/academy-wep/components/base/input.tsx
  apps/academy-wep/components/base/separator.tsx
  apps/academy-wep/components/base/sheet.tsx
  apps/academy-wep/components/base/sidebar.tsx
  apps/academy-wep/components/base/skeleton.tsx
  apps/academy-wep/components/base/tooltip.tsx
  apps/academy-wep/components/page/achivement.tsx
  apps/academy-wep/components/sections/feature-card.tsx
  apps/academy-wep/components/sections/why-choose.tsx
  apps/academy-wep/components/shared/footer.tsx
  apps/academy-wep/components/shared/sidebar.tsx
  apps/academy-wep/components/ui/button.tsx
  apps/academy-wep/components/ui/cta-button.tsx
  apps/academy-wep/components/ui/featured-learning-paths.tsx
  apps/academy-wep/components/ui/input.tsx
  apps/academy-wep/components/ui/learning-path-card.tsx
  apps/academy-wep/hooks/use-mobile.tsx
  apps/academy-wep/lib/constants/footer.ts
  apps/academy-wep/lib/constants/sidebar.ts
  apps/academy-wep/lib/types/footer.ts
  apps/academy-wep/lib/types/sidebar.ts
  apps/academy-wep/package.json
  apps/academy-wep/public/images/kindfi-org.png
  apps/academy-wep/tailwind.config.ts
Labels: feature, webapp, frontend, ODHack12, May Be Rewarded, academy

#363 Feat/ready to earn more badges section
  apps/academy-wep/app/page.tsx
  apps/academy-wep/components/ready-to-earn.tsx
Labels: enhancement, feature, webapp, frontend, academy

#368 Feature: Create Comments Section
  apps/web/app/(routes)/comments/page.tsx
  apps/web/components/base/avatar.tsx
  apps/web/components/base/textarea.tsx
  apps/web/components/pages/comments/comments-tab.tsx
  apps/web/components/pages/comments/project-details.tsx
  apps/web/components/qa-section/ask-question-box.tsx
  apps/web/components/qa-section/load-more-button.tsx
  apps/web/components/qa-section/qa.tsx
  apps/web/components/qa-section/question-card.tsx
  apps/web/components/sections/comments/ask-question-box.tsx
  apps/web/components/sections/comments/comments-list.tsx
  apps/web/components/sections/comments/load-more-button.tsx
  apps/web/components/sections/comments/project-comments-section.tsx
  apps/web/package.json
  bun.lock
Labels: enhancement, feature, webapp, frontend

#346 Feat/filters section
  apps/academy-wep/.env.sample
  apps/academy-wep/.gitignore
  apps/academy-wep/app/globals.css
  apps/academy-wep/app/layout.tsx
  apps/academy-wep/app/page.tsx
  apps/academy-wep/components/base/badge.tsx
  apps/academy-wep/components/base/button.tsx
  apps/academy-wep/components/base/collapsible.tsx
  apps/academy-wep/components/base/input.tsx
  apps/academy-wep/components/base/separator.tsx
  apps/academy-wep/components/base/sheet.tsx
  apps/academy-wep/components/base/sidebar.tsx
  apps/academy-wep/components/base/skeleton.tsx
  apps/academy-wep/components/base/tooltip.tsx
  apps/academy-wep/components/page/achivement.tsx
  apps/academy-wep/components/ready-to-earn.tsx
  apps/academy-wep/components/sections/feature-card.tsx
  apps/academy-wep/components/sections/why-choose.tsx
  apps/academy-wep/components/shared/footer.tsx
  apps/academy-wep/components/shared/sidebar.tsx
  apps/academy-wep/components/ui/category-filter.tsx
  apps/academy-wep/components/ui/cta-button.tsx
  apps/academy-wep/components/ui/featured-learning-paths.tsx
  apps/academy-wep/components/ui/filter-button.tsx
  apps/academy-wep/components/ui/filters-section.tsx
  apps/academy-wep/components/ui/level-filter.tsx
  apps/academy-wep/components/ui/popular-topics.tsx
  apps/academy-wep/components/ui/reset-button.tsx
  apps/academy-wep/hooks/use-mobile.tsx
  apps/academy-wep/lib/constants/footer.ts
  apps/academy-wep/lib/constants/sidebar.ts
  apps/academy-wep/lib/types/footer.ts
  apps/academy-wep/lib/types/sidebar.ts
  apps/academy-wep/package.json
  apps/academy-wep/tailwind.config.ts
  bun.lock
Labels: enhancement, feature, webapp, frontend

#375 feat: learning materials section
  apps/academy-wep/.gitignore
  apps/academy-wep/app/layout.tsx
  apps/academy-wep/app/learn/page.tsx
  apps/academy-wep/app/page.tsx
  apps/academy-wep/components/Achivement.tsx
  apps/academy-wep/components/base/button.tsx
  apps/academy-wep/components/base/card.tsx
  apps/academy-wep/components/base/input.tsx
  apps/academy-wep/components/base/tabs.tsx
  apps/academy-wep/components/hero-section.tsx
  apps/academy-wep/components/knowledge-resources/knowledge-resources.tsx
  apps/academy-wep/components/knowledge-resources/resource-card.tsx
  apps/academy-wep/components/knowledge-resources/search-bar.tsx
  apps/academy-wep/components/learn/learning-materials.tsx
  apps/academy-wep/components/learn/learning-module-card.tsx
  apps/academy-wep/components/learn/resource-card.tsx
  apps/academy-wep/components/learn/tab-selector.tsx
  apps/academy-wep/components/newsletter-subscription.tsx
  apps/academy-wep/components/page/achivement.tsx
  apps/academy-wep/components/sections/feature-card.tsx
  apps/academy-wep/components/ui/category-filter.tsx
  apps/academy-wep/components/ui/featured-learning-paths.tsx
  apps/academy-wep/components/ui/filters-section.tsx
  apps/academy-wep/components/ui/icon.tsx
  apps/academy-wep/components/ui/learning-path-card.tsx
  apps/academy-wep/components/ui/popular-topics.tsx
  apps/academy-wep/components/ui/progress.tsx
  apps/academy-wep/components/ui/stats-display.tsx
  apps/academy-wep/data/achivement-data.ts
  apps/academy-wep/package.json
  apps/academy-wep/public/images/blockchain-basics.jpg
  apps/academy-wep/public/images/blockchain-transparency.jpg
  apps/academy-wep/public/images/blockchain.jpg
  apps/academy-wep/public/images/crowdfunding.png
  apps/academy-wep/public/images/setup-stellar-wallet.png
  apps/academy-wep/public/images/stellar-blockchain.avif
  apps/academy-wep/public/images/stellar-wallets.webp
  apps/academy-wep/public/images/xlm.png
Labels: enhancement, feature, webapp, frontend, ODHack12, academy

#354 Feat/qa section
  apps/web/app/(routes)/projects/page.tsx
  apps/web/app/qa/pages.tsx
  apps/web/components/pages/project/project-information/project-detail-view.tsx
  apps/web/components/pages/project/project-qa/ask-question-box.tsx
  apps/web/components/pages/project/project-qa/index.tsx
  apps/web/components/pages/project/project-qa/load-more-button.tsx
  apps/web/components/pages/project/project-qa/question-card.tsx
  apps/web/package.json
Labels: feature, webapp, frontend

#373 Feat: creating community section
  apps/academy-wep/app/page.tsx
  apps/academy-wep/bun.lock
  apps/academy-wep/components/CTAButtons.tsx
  apps/academy-wep/components/CommunitySection.tsx
  apps/academy-wep/components/CommunityStats.tsx
  apps/academy-wep/components/base/button.tsx
  bun.lock
Labels: feature, webapp, frontend, academy

#356 feat: passkey-ui-accessibility
  apps/web/app/(auth-pages)/sign-in/page.tsx
  apps/web/app/(auth-pages)/sign-up/page.tsx
Labels: enhancement, webapp, frontend

#384 [academy-web] Feat: Create All Resources Section
  apps/academy-wep/app/resources/page.tsx
  apps/academy-wep/components/base/dropdown-menu.tsx
  apps/academy-wep/components/base/progress.tsx
  apps/academy-wep/components/page/resources.tsx
  apps/academy-wep/components/sections/resources/all-resources.tsx
  apps/academy-wep/components/sections/resources/filter-panel.tsx
  apps/academy-wep/components/sections/resources/resource-card.tsx
  apps/academy-wep/components/shared/sidebar.tsx
  apps/academy-wep/components/ui/learning-path-card.tsx
  apps/academy-wep/hooks/resources/use-resource-counts.ts
  apps/academy-wep/hooks/resources/use-resource-filters.ts
  apps/academy-wep/lib/constants/footer.ts
  apps/academy-wep/lib/constants/sidebar.ts
  apps/academy-wep/lib/mock-data/resources.mock.ts
  apps/academy-wep/lib/types/footer.types.ts
  apps/academy-wep/lib/types/resources.types.ts
  apps/academy-wep/lib/types/sidebar.types.ts
  apps/academy-wep/lib/utils/resources/get-type-icon.tsx
  apps/academy-wep/package.json
Labels: enhancement, difficulty: medium, feature, webapp, frontend, ODHack12, May Be Rewarded, academy

#381 Implement Project Detail Page for KindFi
  apps/web/app/(routes)/project/[projectId]/page.tsx
  apps/web/app/(routes)/projects/page.tsx
  apps/web/components/ProjectVideo.tsx
  apps/web/components/pages/project/project-information/project-detail-view.tsx
  apps/web/components/pages/project/project-information/project-details.tsx
  apps/web/components/pages/project/project-information/project-milestone.tsx
  apps/web/components/pages/project/project-information/similar-projects.tsx
  apps/web/lib/types/projects.types.ts
  apps/web/package.json
  apps/web/styles/globals.css
Labels: enhancement, difficulty: medium, feature, webapp, frontend

#385 feat: add Learning Journey Section
  apps/academy-wep/app/learn/page.tsx
  apps/academy-wep/app/page.tsx
  apps/academy-wep/components/CTAButtons.tsx
  apps/academy-wep/components/CommunitySection.tsx
  apps/academy-wep/components/CommunityStats.tsx
  apps/academy-wep/components/Learning-Journey/CTAButtons.tsx
  apps/academy-wep/components/Learning-Journey/LearningJourney.tsx
  apps/academy-wep/components/Learning-Journey/NextLessonCard.tsx
  apps/academy-wep/components/Learning-Journey/ProgressBar.tsx
  apps/academy-wep/components/learn/learning-materials.tsx
  apps/academy-wep/components/learn/learning-module-card.tsx
  apps/academy-wep/components/learn/resource-card.tsx
  apps/academy-wep/components/learn/tab-selector.tsx
Labels: enhancement, feature, webapp, frontend, academy
