Repository kindfi-org/kindfi, pull requests merged in 2025-01, with the labels that each got.

#68 Add proper keys to lists
  apps/web/app/not-found.tsx
  apps/web/components/pages/home.tsx
  apps/web/components/sections/home/community-section.tsx
  apps/web/components/sections/home/creator-section.tsx
  apps/web/components/sections/home/hero-section.tsx
  apps/web/components/sections/home/invest-models-section.tsx
  apps/web/components/sections/home/journey-section.tsx
  apps/web/components/sections/home/participate-section.tsx
  apps/web/components/sections/home/projects-component.tsx
  apps/web/components/sections/home/showcast-section.tsx
  apps/web/components/shared/feauture-card.tsx
  apps/web/components/shared/investment-model-card.tsx
  apps/web/components/shared/layout/header/navigation.tsx
  apps/web/components/shared/project-card.tsx
  apps/web/lib/config/navigation.ts
  docs/SUMMARY.md
Labels: documentation, enhancement

#73 [web] Feat: Add Main Navigation ARIA Labels
  apps/web/components/base/navigation-menu.tsx
  apps/web/components/shared/layout/header/navigation.tsx
Labels: documentation, enhancement

#79 feat: enhance forms inputs accessibility
  apps/web/app/(auth-pages)/sign-in/page.tsx
  apps/web/app/(auth-pages)/sign-up/page.tsx
  apps/web/components/shared/layout/footer/footer.tsx
  apps/web/hooks/use-form-validation.ts
Labels: documentation, enhancement

#76 feat: adding semantic html for dialog
  apps/web/.env.sample
  apps/web/components/base/dialog.tsx
Labels: documentation, enhancement

#97 Feat: Create project details components for project page
  apps/web/app/(routes)/project/page.tsx
  apps/web/components/base/image.tsx
  apps/web/components/base/tab-navigation.tsx
  apps/web/components/sections/project/about-project.tsx
  apps/web/components/sections/project/impact-cards.tsx
  apps/web/components/sections/project/media-player.tsx
  apps/web/components/sections/project/project-overview.tsx
  apps/web/components/sections/project/project-showcase.tsx
  apps/web/components/sections/project/project-updates.tsx
  apps/web/components/sections/project/section-container.tsx
  apps/web/components/sections/project/success-gallery.tsx
  apps/web/components/sections/project/supporter-updates.tsx
  apps/web/components/sections/project/timeline.tsx
  apps/web/components/sections/project/your-impact.tsx
  apps/web/lib/constants/mock-data/mock-projects.ts
  apps/web/package.json
  apps/web/public/images/image.png
  apps/web/public/images/video.png
Labels: documentation, enhancement, webapp

#95 feat(alert):Implemented-aria-live-regions-#34
  apps/web/components/base/alert-dialog.tsx
Labels: documentation, enhancement

#89 update: improvementes on navigation menu
  apps/web/components/base/navigation-menu.tsx
  apps/web/components/shared/layout/header/navigation.tsx
Labels: documentation, enhancement

#82 [web] Rename, organize and implement lazy loading in home sections
  apps/web/components/icons/illustrations.tsx
  apps/web/components/pages/home.tsx
  apps/web/components/sections/home/community-section.tsx
  apps/web/components/sections/home/community.tsx
  apps/web/components/sections/home/creator-section.tsx
  apps/web/components/sections/home/final-cta.tsx
  apps/web/components/sections/home/hero-section.tsx
  apps/web/components/sections/home/hero.tsx
  apps/web/components/sections/home/highlighted-projects.tsx
  apps/web/components/sections/home/how-it-works.tsx
  apps/web/components/sections/home/invest-models-section.tsx
  apps/web/components/sections/home/investor-guide-section.tsx
  apps/web/components/sections/home/join-us.tsx
  apps/web/components/sections/home/journey-section.tsx
  apps/web/components/sections/home/new-user-guide.tsx
  apps/web/components/sections/home/participate-section.tsx
  apps/web/components/sections/home/platform-overview.tsx
  apps/web/components/sections/home/projects-component.tsx
  apps/web/components/sections/home/showcast-section.tsx
  apps/web/components/sections/home/user-journey.tsx
  apps/web/components/shared/investment-model-card.tsx
  apps/web/components/shared/platform-feature-card.tsx
  apps/web/components/shared/web3-feature-card.tsx
  apps/web/lib/constants/animations.ts
  apps/web/lib/mock-data/mock-community-section.tsx
  apps/web/lib/mock-data/mock-final-cta-section.tsx
  apps/web/lib/mock-data/mock-hero-section.tsx
  apps/web/lib/mock-data/mock-how-it-works-section.tsx
  apps/web/lib/mock-data/mock-join-us-section.tsx
  apps/web/lib/mock-data/mock-new-user-guide.tsx
  apps/web/lib/mock-data/mock-platform-overview.tsx
  apps/web/lib/mock-data/mock-projects.ts
  apps/web/lib/mock-data/mock-user-journey.tsx
  apps/web/lib/types/home.types.ts
  apps/web/tailwind.config.ts
Labels: documentation, enhancement, webapp, chore

#99 Implement achievement component
  apps/web/app/(routes)/dashboard/page.tsx
  apps/web/app/(routes)/project/page.tsx
  apps/web/components/base/alert-dialog.tsx
  apps/web/components/base/dialog.tsx
  apps/web/components/base/image.tsx
  apps/web/components/base/pagination.tsx
  apps/web/components/base/tab-navigation.tsx
  apps/web/components/fallbacks/error-fallback.tsx
  apps/web/components/fallbacks/loading-fallback.tsx
  apps/web/components/pages/achievements.tsx
  apps/web/components/sections/achievements/achievement-card.tsx
  apps/web/components/sections/achievements/achievement-grid.tsx
  apps/web/components/sections/achievements/nft-card.tsx
  apps/web/components/sections/achievements/stats-section.tsx
  apps/web/components/sections/project/project-overview.tsx
  apps/web/components/shared/pagination.tsx
  apps/web/lib/constants/mock-data/section.ts
  apps/web/lib/types/section.ts
  apps/web/package.json
  apps/web/public/images/nft1.png
  apps/web/public/images/nft2.png
  apps/web/public/images/nft3.png
  apps/web/public/images/nft4.png
  apps/web/public/images/nft5.png
  apps/web/public/images/nft6.png
  apps/web/public/images/nft7.png
  apps/web/public/images/nft8.png
  package.json
Labels: documentation, enhancement, webapp
